version: '3'

services:
  elasticsearch:
      build: elasticsearch\
      container_name: elasticsearch
      volumes:
        - .\elasticsearch\config\config.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      ports:
        - 9200:9200
      environment:
        - "cluster.name=elasticsearch"
        - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
        - "XPACK_SECURITY_ENABLED=false"
      networks:
        - elk
      healthcheck:
        test: "curl http://elasticsearch:9200"
        interval: "1s"
        timeout: "3s"
        retries: 60
  web:
      build:
        dockerfile: Dockerfile
        context: .\
      container_name: web
      restart: always
      volumes:
        - .\web\config.yaml:/usr/share/web/config.yaml
      ports:
        - 5000:5000
      expose:
        - 5000
      networks: 
        - elk
      depends_on:
        - elasticsearch
networks:
  elk:
    driver: bridge